apiVersion: v1
kind: Service
metadata : 
    name : my-service
    labels:
        owner: SafronovDmitry
spec:
    selector:
        project : my-devops-deploy  # Selecting PODS with this label
    ports:
        - name      : app-listener
          protocol  : TCP
          port      : 8080 # Port on LoadBalancer
          targetPort: 80 # Port on POD
    type: LoadBalancer
    